# Generated by Django 5.2.7 on 2025-10-15 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=250)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.card')),
            ],
        ),
    ]
