# Generated by Django 5.2.7 on 2025-10-16 18:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_collection'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.card')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_app.collection')),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='cards',
        ),
        migrations.AddField(
            model_name='collection',
            name='cards',
            field=models.ManyToManyField(through='my_app.CardCollection', to='my_app.card'),
        ),
        
    ]
